# Generated by Django 2.2.5 on 2020-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_number', models.CharField(max_length=10)),
                ('question_content', models.CharField(max_length=500)),
                ('answer_number', models.CharField(max_length=10)),
                ('answer_content', models.CharField(max_length=8000)),
                ('qusetion_type', models.CharField(max_length=50)),
                ('question_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='question_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qusetion_type', models.CharField(max_length=50)),
            ],
        ),
    ]
