# Generated by Django 2.2.5 on 2020-06-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAManagement', '0003_auto_20200528_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_answer',
            old_name='qusetion_type',
            new_name='question_type',
        ),
        migrations.RenameField(
            model_name='question_type',
            old_name='qusetion_type',
            new_name='question_type',
        ),
    ]
